### ISSUE TITLE
v 2.0.8 package is not PackageReference compliant

### ISSUE THREAD

**Issue by jmwolfe** [MrAntix/smtp-impostor#2]
Hello Anthony -

Any possibility you would consider updating your 2.0.8 package for this project in NuGet to use the new standard 'net40' Target Framework Moniker? Your current package uses .NET Framework 4.0 which does not work with the PackageReference style of using Nuget.

net40 would work with package.config.

Yours is the only package out of the 20 I'm using that is using the arcane .NET Framework 4.0 folder name.

Thanks.

**Comment by MrAntix** [comment]
What’s involved?
Would you submit a PR that I could take a look at and push to Nuget?

Another option may be to use version 3, I was planning to package it for Nuget 
However, it’s a rewrite in netcore, so may not be suitable for you

Ant

**Comment by jmwolfe** [comment]
Sorry, I have never published a NuGet package.



Documentation is here: https://docs.microsoft.com/en-us/nuget/nuget-org/publish-a-package



Nuget is not like GitHub... not driven by PR's.   You probably just have to update your old solution to use the new framework then upload it to NuGet.org.



The only real change is that "lib/.Net Framework 4.0" needs to change to lib/net40. You could even take your old package (download from Nuget.org), change that one folder and reupload it.  Since you're the owner of that package, you would need to do it.


And yes, I'm using .NET Framework, so I can't just include .NetCore projects easily.


Thank you!



Jesse


---- On Tue, 21 Jul 2020 14:29:29 -0400 Anthony Johnston <notifications@github.com> wrote ----




What’s involved?
 Would you submit a PR that I could take a look at and push to Nuget?
Another option may be to use version 3, I was planning to package it for Nuget
 However, it’s a rewrite in netcore, so may not be suitable for you
Ant

**Comment by MrAntix** [comment]
Hi Jesse, I had a think and I am not going to do this

The package is legacy and was compliant at the time. 
My worry is that changing it may have side affects that I don’t have time to find or fix.

You could unzip this package, make your changes and host it relatively in a folder referenced in your Nuget.config, but I will leave that to you

All the best, ANT
